CREATE TABLE `blog_posts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`slug` varchar(255) NOT NULL,
	`title` varchar(500) NOT NULL,
	`excerpt` text NOT NULL,
	`content` text NOT NULL,
	`featuredImage` varchar(500),
	`category` varchar(100) NOT NULL,
	`tags` text,
	`authorName` varchar(255) NOT NULL,
	`authorSlug` varchar(255) NOT NULL,
	`readTime` int NOT NULL,
	`status` enum('draft','published','archived') NOT NULL DEFAULT 'draft',
	`metaDescription` varchar(500),
	`createdBy` int NOT NULL,
	`publishedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `blog_posts_id` PRIMARY KEY(`id`),
	CONSTRAINT `blog_posts_slug_unique` UNIQUE(`slug`)
);
--> statement-breakpoint
CREATE TABLE `case_studies` (
	`id` int AUTO_INCREMENT NOT NULL,
	`slug` varchar(255) NOT NULL,
	`title` varchar(500) NOT NULL,
	`clientName` varchar(255) NOT NULL,
	`industry` varchar(100) NOT NULL,
	`service` varchar(100) NOT NULL,
	`summary` text NOT NULL,
	`content` text NOT NULL,
	`featuredImage` varchar(500),
	`metric1Value` varchar(50),
	`metric1Label` varchar(255),
	`metric2Value` varchar(50),
	`metric2Label` varchar(255),
	`metric3Value` varchar(50),
	`metric3Label` varchar(255),
	`tags` text,
	`status` enum('draft','published','archived') NOT NULL DEFAULT 'draft',
	`createdBy` int NOT NULL,
	`publishedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `case_studies_id` PRIMARY KEY(`id`),
	CONSTRAINT `case_studies_slug_unique` UNIQUE(`slug`)
);
--> statement-breakpoint
CREATE TABLE `events` (
	`id` int AUTO_INCREMENT NOT NULL,
	`slug` varchar(255) NOT NULL,
	`title` varchar(500) NOT NULL,
	`eventType` varchar(100) NOT NULL,
	`description` text NOT NULL,
	`content` text NOT NULL,
	`featuredImage` varchar(500),
	`startDate` timestamp NOT NULL,
	`endDate` timestamp,
	`location` varchar(255),
	`registrationUrl` varchar(500),
	`speakers` text,
	`tags` text,
	`status` enum('upcoming','ongoing','completed','cancelled') NOT NULL DEFAULT 'upcoming',
	`createdBy` int NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `events_id` PRIMARY KEY(`id`),
	CONSTRAINT `events_slug_unique` UNIQUE(`slug`)
);
