CREATE TABLE `job_applications` (
	`id` int AUTO_INCREMENT NOT NULL,
	`jobId` int NOT NULL,
	`firstName` varchar(100) NOT NULL,
	`lastName` varchar(100) NOT NULL,
	`email` varchar(320) NOT NULL,
	`phone` varchar(50),
	`linkedinUrl` varchar(500),
	`portfolioUrl` varchar(500),
	`resumeS3Key` varchar(500) NOT NULL,
	`resumeUrl` varchar(1000) NOT NULL,
	`coverLetter` text,
	`referralSource` varchar(255),
	`workAuthorization` varchar(100),
	`willingToRelocate` boolean DEFAULT false,
	`expectedSalary` varchar(100),
	`availableStartDate` varchar(100),
	`additionalNotes` text,
	`status` enum('new','reviewing','phone_screen','interview','offer','hired','rejected','withdrawn') NOT NULL DEFAULT 'new',
	`internalNotes` text,
	`userId` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `job_applications_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `jobs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`slug` varchar(255) NOT NULL,
	`title` varchar(255) NOT NULL,
	`department` varchar(100) NOT NULL,
	`location` varchar(255) NOT NULL,
	`employmentType` varchar(50) NOT NULL,
	`experienceLevel` varchar(50) NOT NULL,
	`salaryRange` varchar(100),
	`summary` text NOT NULL,
	`description` text NOT NULL,
	`requirements` text NOT NULL,
	`niceToHave` text,
	`benefits` text,
	`clearanceRequired` varchar(50) DEFAULT 'None',
	`remoteAllowed` boolean DEFAULT false,
	`applicationDeadline` timestamp,
	`status` enum('draft','published','closed','archived') NOT NULL DEFAULT 'draft',
	`createdBy` int NOT NULL,
	`publishedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `jobs_id` PRIMARY KEY(`id`),
	CONSTRAINT `jobs_slug_unique` UNIQUE(`slug`)
);
